name: build
on:
  push

# Environment
env:
  CI: true
  NODE_VERSION: 10.x
  PYTHON_VERSION: 3.x

# Jobs to run
jobs:

  # Build documentation
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source form GitHub
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: install Python runtime and dependencies
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: install theme and dependencies
        run: |
          pip install -r requirements.txt
          pip install .
          pip install \
            mkdocs-minify-plugin>=0.3 \
            mkdocs-redirects>=1.0

      - name: Build documents
        run: |
          mkdocs build --clean
